#!/bin/bash

cd `dirname $0`

git submodule init
git submodule update

mkdir -p ~/.bin
cp -rf .bin ~

cp .emacs ~
cp .gnus ~
mkdir -p .emacs.d/lisp ~/.emacs.d/lisp
cp -rf .emacs.d/lisp ~/.emacs.d
ln -sf ~/Dropbox/Bookmarks/emacs ~/.emacs.d/bookmarks
rm -f ~/.emacs.elc ~/.emacs.d/lisp/*.elc

cp .profile ~
ln -sf ~/.profile ~/.bashrc

cp .ssh/* ~/.ssh

mkdir -p ~/.subversion
cp .subversion/config ~/.subversion/

cp .gitconfig ~
cp .gitignore ~
git config --global core.excludesfile ~/.gitignore
